package com.jlboat.phone.util;
public class ServiceNames {
    public static String AddManuPoint;
    public static String AddPoint;
    public static String AddPointsGlobalplan;
    public static String CalculateOdom;
    public static String ChangeMap;
    public static String Chargpriority;
    public static String CleanAreaService;
    public static String ClearMap;
    public static String CocoNum;
    public static String CurrentPosint;
    public static String DeleteAllBags;
    public static String DeleteAllMap;
    public static String DeleteAlllogs;
    public static String DeleteFloor;
    public static String DeleteMap;
    public static String DeletePointsGlobalPlan;
    public static String DeleteTestPoint;
    public static String DiyPath;
    public static String EraserMode;
    public static String ExecutePath;
    public static String GetBags;
    public static String GetESPStatus;
    public static String GetLogs;
    public static String GetLoraStatus;
    public static String GetMaps;
    public static String Goal;
    public static String Mode;
    public static String MoveCalibration;
    public static String NaviGoal;
    public static String NaviInfo;
    public static String NaviPoints;
    public static String NaviTest;
    public static String Navicmd;
    public static String RebuildMap;
    public static String RegionService;
    public static String Relocation;
    public static String RenameFloor;
    public static String RenameMapName;
    public static String RenamePath;
    public static String RenamePoint;
    public static String SaveMap;
    public static String ShapeService;
    public static String Ssh;
    public static String UpdatePoint;
    public static String Wifi;
    public static String robotConfig;
    public static String robotConfigSet;
    public static String robotCream;
    public static String robotCreamSet;
    public static String robotSafe;
    public static String robotSafeSet;
    public static String robotSonar;
    public static String robotSonarSet;
    public static String robotSpeed;
    public static String robotSpeedSet;
    public static String robotTestDriver;
    public static String saveEraseMap;
    public static String saveExtMap;
    public static String slamDownMap;

    static ServiceNames()
    {
        com.jlboat.phone.util.ServiceNames.GetLoraStatus = "get_lorastatus";
        com.jlboat.phone.util.ServiceNames.GetESPStatus = "get_espstatus";
        com.jlboat.phone.util.ServiceNames.CalculateOdom = "calculate_odom_service";
        com.jlboat.phone.util.ServiceNames.MoveCalibration = "move_calibration";
        com.jlboat.phone.util.ServiceNames.NaviTest = "set_navi_test";
        com.jlboat.phone.util.ServiceNames.NaviInfo = "/navi_info";
        com.jlboat.phone.util.ServiceNames.CocoNum = "/set_coconum";
        com.jlboat.phone.util.ServiceNames.Wifi = "/set_wifi";
        com.jlboat.phone.util.ServiceNames.Mode = "/set_mode";
        com.jlboat.phone.util.ServiceNames.Navicmd = "/set_navi_cmd";
        com.jlboat.phone.util.ServiceNames.CurrentPosint = "/get_position";
        com.jlboat.phone.util.ServiceNames.Chargpriority = "/set_charpriority";
        com.jlboat.phone.util.ServiceNames.GetMaps = "get_maps";
        com.jlboat.phone.util.ServiceNames.ChangeMap = "/publish_map";
        com.jlboat.phone.util.ServiceNames.ClearMap = "clear_map";
        com.jlboat.phone.util.ServiceNames.RebuildMap = "rebuild_map";
        com.jlboat.phone.util.ServiceNames.SaveMap = "save_map";
        com.jlboat.phone.util.ServiceNames.saveEraseMap = "saveerase_map";
        com.jlboat.phone.util.ServiceNames.saveExtMap = "save_ext_map";
        com.jlboat.phone.util.ServiceNames.EraserMode = "set_erasermode";
        com.jlboat.phone.util.ServiceNames.DeleteMap = "delete_map";
        com.jlboat.phone.util.ServiceNames.DeleteFloor = "delete_floor";
        com.jlboat.phone.util.ServiceNames.RenameFloor = "rename_floor";
        com.jlboat.phone.util.ServiceNames.DeleteAllMap = "delete_allmap";
        com.jlboat.phone.util.ServiceNames.RenameMapName = "rename_map";
        com.jlboat.phone.util.ServiceNames.NaviPoints = "list_navi_points";
        com.jlboat.phone.util.ServiceNames.AddPoint = "point_set";
        com.jlboat.phone.util.ServiceNames.DeleteTestPoint = "delete_test_point";
        com.jlboat.phone.util.ServiceNames.RenamePoint = "point_rename";
        com.jlboat.phone.util.ServiceNames.UpdatePoint = "point_update";
        com.jlboat.phone.util.ServiceNames.Goal = "set_goal";
        com.jlboat.phone.util.ServiceNames.NaviGoal = "navi_targegoalplan";
        com.jlboat.phone.util.ServiceNames.ShapeService = "set_shape";
        com.jlboat.phone.util.ServiceNames.RegionService = "set_region";
        com.jlboat.phone.util.ServiceNames.DiyPath = "set_globalplan";
        com.jlboat.phone.util.ServiceNames.RenamePath = "rename_globalplan";
        com.jlboat.phone.util.ServiceNames.AddPointsGlobalplan = "addpoints_globalplan";
        com.jlboat.phone.util.ServiceNames.DeletePointsGlobalPlan = "deletepoints_globalplan";
        com.jlboat.phone.util.ServiceNames.ExecutePath = "move_base/execute_path";
        com.jlboat.phone.util.ServiceNames.GetLogs = "get_log";
        com.jlboat.phone.util.ServiceNames.DeleteAlllogs = "delete_allbags";
        com.jlboat.phone.util.ServiceNames.GetBags = "bag_list";
        com.jlboat.phone.util.ServiceNames.DeleteAllBags = "delete_allbags";
        com.jlboat.phone.util.ServiceNames.Ssh = "robot_ssh";
        com.jlboat.phone.util.ServiceNames.Relocation = "set_relocation";
        com.jlboat.phone.util.ServiceNames.AddManuPoint = "pointmanu_set";
        com.jlboat.phone.util.ServiceNames.slamDownMap = "import_configs";
        com.jlboat.phone.util.ServiceNames.CleanAreaService = "set_cleanArea";
        com.jlboat.phone.util.ServiceNames.robotSonar = "robot_sonarlist";
        com.jlboat.phone.util.ServiceNames.robotSonarSet = "robot_sonarset";
        com.jlboat.phone.util.ServiceNames.robotSpeed = "robot_speedlist";
        com.jlboat.phone.util.ServiceNames.robotSpeedSet = "robot_speedset";
        com.jlboat.phone.util.ServiceNames.robotSafe = "navigation_safesetlist";
        com.jlboat.phone.util.ServiceNames.robotSafeSet = "navigation_safeset";
        com.jlboat.phone.util.ServiceNames.robotCream = "navigation_Creamsetlist";
        com.jlboat.phone.util.ServiceNames.robotCreamSet = "navigation_Creamset";
        com.jlboat.phone.util.ServiceNames.robotConfig = "get_configs";
        com.jlboat.phone.util.ServiceNames.robotConfigSet = "set_configs";
        com.jlboat.phone.util.ServiceNames.robotTestDriver = "test_driver_service";
        return;
    }

    public ServiceNames()
    {
        return;
    }
}
